// frontend/src/pages/Dashboard.tsx
import React from 'react';

const Dashboard: React.FC = () => {
  return (
    <div className="dashboard-page glass-card" style={{ padding: '32px', height: '100%' }}>
      <h1>CRM Dashboard</h1>
      <div className="stats-grid" style={{ 
        display: 'grid', 
        gridTemplateColumns: 'repeat(4, 1fr)', 
        gap: '20px', 
        marginTop: '24px' 
      }}>
        <div className="stat-card glass-card" style={{ padding: '24px', textAlign: 'center' }}>
          <h3 style={{ fontSize: '0.9rem', color: 'var(--text-dim)', marginBottom: '8px' }}>Total Leads</h3>
          <p style={{ fontSize: '1.8rem', fontWeight: 600 }}>42</p>
        </div>
        <div className="stat-card glass-card" style={{ padding: '24px', textAlign: 'center' }}>
          <h3 style={{ fontSize: '0.9rem', color: 'var(--text-dim)', marginBottom: '8px' }}>Hot Leads</h3>
          <p style={{ fontSize: '1.8rem', fontWeight: 600 }}>12</p>
        </div>
        <div className="stat-card glass-card" style={{ padding: '24px', textAlign: 'center' }}>
          <h3 style={{ fontSize: '0.9rem', color: 'var(--text-dim)', marginBottom: '8px' }}>New Orders</h3>
          <p style={{ fontSize: '1.8rem', fontWeight: 600 }}>5</p>
        </div>
        <div className="stat-card glass-card" style={{ padding: '24px', textAlign: 'center' }}>
          <h3 style={{ fontSize: '0.9rem', color: 'var(--text-dim)', marginBottom: '8px' }}>Conv. Rate</h3>
          <p style={{ fontSize: '1.8rem', fontWeight: 600 }}>15%</p>
        </div>
      </div>
    </div>
  );
};

export default Dashboard;

// frontend/src/app/dashboard/dashboard.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-dashboard',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div class="dashboard glass-card">
      <h1>CRM Dashboard</h1>
      <div class="stats-grid">
        <div class="stat-card"><h3>Total Leads</h3><p>42</p></div>
        <div class="stat-card"><h3>Hot Leads</h3><p>12</p></div>
        <div class="stat-card"><h3>New Orders</h3><p>5</p></div>
        <div class="stat-card"><h3>Conv. Rate</h3><p>15%</p></div>
      </div>
    </div>
  `,
  styles: [`
    .dashboard { padding: 32px; height: 100%; }
    .stats-grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 20px; margin-top: 24px; }
    .stat-card { background: var(--glass); padding: 24px; border-radius: 12px; border: 1px solid var(--glass-border); text-align: center; }
    .stat-card h3 { margin: 0; font-size: 0.9rem; color: var(--text-dim); }
    .stat-card p { margin: 12px 0 0; font-size: 1.8rem; font-weight: 600; }
  `]
})
export class DashboardComponent {}
